template:
  path: "codeocean.template.yaml"
stack_name: "codeocean"
stack_tags:
  OwnerEmail: "it@sagebase.org"
  CostCenter: "Platform Infrastructure / 990300"
parameters:
  pVpcCIDR: "10.15.0.0/16"
  pPrivateSubnet1CIDR: "10.15.0.0/20"
  pPublicSubnet1CIDR: "10.15.96.0/20"
  pPrivateSubnet2CIDR: "10.15.16.0/20"
  pPublicSubnet2CIDR: "10.15.112.0/20"
  pPrivateSubnet3CIDR: "10.15.32.0/20"
  pPublicSubnet3CIDR: "10.15.128.0/20"
  pPrivateSubnet4CIDR: "10.15.48.0/20"
  pPublicSubnet4CIDR: "10.15.144.0/20"
  pPrivateSubnet5CIDR: "10.15.64.0/20"
  pPublicSubnet5CIDR: "10.15.160.0/20"
  pPrivateSubnet6CIDR: "10.15.80.0/20"
  pPublicSubnet6CIDR: "10.15.176.0/20"
  pDnsRootDomain: "sageit.org"