template:
  path: "codeocean.template.yaml"
stack_name: "codeocean"
stack_tags:
  OwnerEmail: "it@sagebase.org"
  CostCenter: "Platform Infrastructure / 990300"
dependencies:
  - "prod/codeocean-sageit-org-hosted-zone.yaml"
parameters:
  pNewVpcAvailabilityZone1: "us-east-1a"
  pNewVpcAvailabilityZone2: "us-east-1b"
  pDnsRootDomain: "sageit.org"
  pVpcCIDR: "10.15.0.0/16"
  pPrivateSubnet1CIDR: "10.15.0.0/20"
  pPrivateSubnet2CIDR: "10.15.16.0/20"
  pPublicSubnet1CIDR: "10.15.96.0/20"
  pPublicSubnet2CIDR: "10.15.112.0/20"
  pHostedZoneId: !stack_output_external "codeocean-sageit-org-hosted-zone::HostedZoneId"
